model_name: gpt2-large
max_length: 256
seed: 42
lambda_reg: 0.0001
knn_k: 10
artifacts_dir: artifacts_gpt2_large_multi
embeddings_dir: embeddings/gpt2_large_multi
metrics_dir: metrics/gpt2_large_multi
graphs_dir: graphs
geodesic_dir: geodesic
plots_dir: plots
curvature_dir: curvature/gpt2_large_multi
curvature_2d_dir: curvature_2d/gpt2_large_multi
dataset:
  name: multi_source
  config: default
  split: train
num_datasets: 10
samples_per_dataset: 15
